/* Invitation token stays in a URL fragment/sessionStorage, never in analytics or referrers. */
(function(){
 'use strict';
 const copy={
 de:{title:'Dein Testzugang',intro:'Einmal aktivieren, danach mit deinem eigenen Passwort anmelden.',passwordLabel:'Passwort festlegen',confirmLabel:'Passwort wiederholen',passwordHelp:'Mindestens 8 Zeichen mit Gross- und Kleinbuchstaben, Zahl und Sonderzeichen.',termsBefore:'Ich akzeptiere die',terms:'Nutzungsbedingungen',privacyBefore:'und habe die',privacy:'Datenschutzerklärung',termsAfter:' gelesen.',submit:'Testzugang aktivieren',renew:'Neuen Einladungslink anfordern',ready:'Dein Zugang ist bereit',next:'Lade LignoCAD Tragwerk für Windows herunter und installiere es.',download:'Für Windows herunterladen',loginHelp:'Öffne das Programm und melde dich mit deiner E-Mail-Adresse und dem gerade festgelegten Passwort an.',login:'Zum Konto',support:'Fragen? Schreib an info@lignoai.ch.',loading:'Einladung wird geprüft …',busy:'Zugang wird aktiviert …',sent:'Ein neuer Link wurde an die hinterlegte E-Mail-Adresse gesendet. Öffne die neueste Nachricht.',mismatch:'Die Passwörter stimmen nicht überein.',free:'Dein Testpartner-Zugang ist kostenlos.',months:'Freigeschaltet für {n} Monate ab Aktivierung.',unlimited:'Die Freischaltung gilt bis zum Widerruf.',expired:'Dieser Link ist abgelaufen. Fordere einen neuen an.',invalid_invitation:'Dieser Link ist ungültig oder wurde ersetzt. Verwende die neueste Einladung oder melde dich bei Sebastian.',already_accepted:'Dieser Zugang wurde bereits aktiviert. Du kannst dich mit deinem Passwort anmelden.',busy_or_rate_limited:'Bitte warte kurz und versuche es nochmals. Falls bereits mehrere Mails angefordert wurden, melde dich bei Sebastian.',weak_password:'Bitte beachte die Anforderungen an das Passwort.',consent_required:'Bitte akzeptiere die Nutzungsbedingungen.',account_exists:'Für diese Adresse besteht bereits ein Konto. Melde dich bei Sebastian, damit er die Lizenz zuordnen kann.',failed:'Das hat nicht geklappt. Versuche es nochmals oder melde dich bei Sebastian.'},
 fr:{title:'Votre accès test',intro:'Activez votre accès, puis connectez-vous avec votre propre mot de passe.',passwordLabel:'Choisir un mot de passe',confirmLabel:'Répéter le mot de passe',passwordHelp:'Au moins 8 caractères avec majuscule, minuscule, chiffre et caractère spécial.',termsBefore:'J’accepte les',terms:'conditions d’utilisation',privacyBefore:'et j’ai lu la',privacy:'déclaration de confidentialité',termsAfter:'.',submit:'Activer mon accès test',renew:'Demander un nouveau lien',ready:'Votre accès est prêt',next:'Téléchargez et installez LignoCAD Tragwerk pour Windows.',download:'Télécharger pour Windows',loginHelp:'Ouvrez le logiciel et connectez-vous avec votre adresse e-mail et le mot de passe choisi.',login:'Mon compte',support:'Des questions ? Écrivez à info@lignoai.ch.',loading:'Vérification de l’invitation …',busy:'Activation de l’accès …',sent:'Un nouveau lien a été envoyé à l’adresse enregistrée. Ouvrez le dernier message.',mismatch:'Les mots de passe ne correspondent pas.',free:'Votre accès partenaire de test est gratuit.',months:'Accès pendant {n} mois après activation.',unlimited:'L’accès reste valable jusqu’à révocation.',expired:'Ce lien a expiré. Demandez-en un nouveau.',invalid_invitation:'Ce lien est invalide ou a été remplacé. Utilisez la dernière invitation ou contactez Sebastian.',already_accepted:'Cet accès est déjà activé. Connectez-vous avec votre mot de passe.',busy_or_rate_limited:'Patientez puis réessayez. Si vous avez demandé plusieurs messages, contactez Sebastian.',weak_password:'Respectez les exigences du mot de passe.',consent_required:'Veuillez accepter les conditions d’utilisation.',account_exists:'Un compte existe déjà pour cette adresse. Contactez Sebastian pour attribuer la licence.',failed:'L’opération a échoué. Réessayez ou contactez Sebastian.'},
 it:{title:'Il tuo accesso di prova',intro:'Attiva il tuo accesso, poi accedi con la tua password.',passwordLabel:'Scegli una password',confirmLabel:'Ripeti la password',passwordHelp:'Almeno 8 caratteri con maiuscola, minuscola, numero e carattere speciale.',termsBefore:'Accetto le',terms:'condizioni di utilizzo',privacyBefore:'e ho letto l’',privacy:'informativa sulla privacy',termsAfter:'.',submit:'Attiva accesso di prova',renew:'Richiedi un nuovo link',ready:'Il tuo accesso è pronto',next:'Scarica e installa LignoCAD Tragwerk per Windows.',download:'Scarica per Windows',loginHelp:'Apri il programma e accedi con il tuo indirizzo e-mail e la password appena scelta.',login:'Il mio account',support:'Domande? Scrivi a info@lignoai.ch.',loading:'Verifica dell’invito …',busy:'Attivazione dell’accesso …',sent:'Un nuovo link è stato inviato all’indirizzo registrato. Apri il messaggio più recente.',mismatch:'Le password non corrispondono.',free:'Il tuo accesso come partner di prova è gratuito.',months:'Accesso per {n} mesi dall’attivazione.',unlimited:'L’accesso è valido fino alla revoca.',expired:'Questo link è scaduto. Richiedine uno nuovo.',invalid_invitation:'Questo link non è valido o è stato sostituito. Usa l’ultimo invito o contatta Sebastian.',already_accepted:'Questo accesso è già attivo. Accedi con la tua password.',busy_or_rate_limited:'Attendi e riprova. Se hai richiesto più messaggi, contatta Sebastian.',weak_password:'Rispetta i requisiti della password.',consent_required:'Accetta le condizioni di utilizzo.',account_exists:'Esiste già un account per questo indirizzo. Contatta Sebastian per assegnare la licenza.',failed:'Operazione non riuscita. Riprova o contatta Sebastian.'},
 en:{title:'Your test access',intro:'Activate once, then sign in with your own password.',passwordLabel:'Choose a password',confirmLabel:'Repeat password',passwordHelp:'At least 8 characters with an uppercase letter, lowercase letter, number and special character.',termsBefore:'I accept the',terms:'Terms of Use',privacyBefore:'and have read the',privacy:'Privacy Policy',termsAfter:'.',submit:'Activate test access',renew:'Request a new invitation link',ready:'Your access is ready',next:'Download and install LignoCAD Tragwerk for Windows.',download:'Download for Windows',loginHelp:'Open the application and sign in with your email address and the password you just set.',login:'My account',support:'Questions? Email info@lignoai.ch.',loading:'Checking invitation …',busy:'Activating access …',sent:'A new link has been sent to the registered email address. Open the latest message.',mismatch:'The passwords do not match.',free:'Your test partner access is free.',months:'Access for {n} months from activation.',unlimited:'Access remains valid until revoked.',expired:'This link has expired. Request a new one.',invalid_invitation:'This link is invalid or has been replaced. Use the latest invitation or contact Sebastian.',already_accepted:'This access has already been activated. Sign in with your password.',busy_or_rate_limited:'Wait briefly and try again. If you have requested several emails, contact Sebastian.',weak_password:'Please follow the password requirements.',consent_required:'Please accept the Terms of Use.',account_exists:'An account already exists for this address. Contact Sebastian to assign the licence.',failed:'Something went wrong. Try again or contact Sebastian.'}
 };
 const $=id=>document.getElementById(id),query=new URLSearchParams(location.search),fragment=new URLSearchParams(location.hash.slice(1));
 let lang=copy[query.get('lang')]?query.get('lang'):'de',t=copy[lang],token=fragment.get('token')||sessionStorage.getItem('lignoai-invitation')||'',termsVersion='',invitation=null;
 if(fragment.has('token')){sessionStorage.setItem('lignoai-invitation',token);history.replaceState(null,'',location.pathname+location.search);}
 function translate(){t=copy[lang];document.documentElement.lang=lang;document.title=t.title+' · LignoAI';$('language').value=lang;for(const id of ['title','intro','passwordLabel','confirmLabel','passwordHelp','termsBefore','terms','privacyBefore','privacy','termsAfter','submit','renew','ready','next','download','loginHelp','login','support'])$(id).textContent=t[id];const base=lang==='de'?'/':'/'+lang+'/';$('terms').href=base+'#/nutzungsbedingungen';$('privacy').href=base+'#/datenschutz';$('login').href=base+'#/anmelden';if(invitation)$('licence').textContent=t.free+' '+(invitation.license_months===null?t.unlimited:t.months.replace('{n}',invitation.license_months));}
 function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
 async function api(action,extra={}){const response=await fetch('https://djijagmwottlscxguimc.supabase.co/functions/v1/partner-invitations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,token,...extra}),signal:AbortSignal.timeout(45000)});const result=await response.json();if(!response.ok)throw Error(result.error||'failed');return result;}
 function error(e){const code=e.message;status(t[code]||t.failed,true);$('renew').hidden=code!=='expired';if(code==='already_accepted'){$('done').hidden=false;$('activate').hidden=true;sessionStorage.removeItem('lignoai-invitation');token='';}}
 async function inspect(){status(t.loading);try{const data=await api('inspect');invitation=data.invitation;termsVersion=data.terms_version;$('name').textContent=invitation.first_name+' '+invitation.last_name;$('organization').textContent=invitation.organization;$('email').textContent=invitation.email;translate();status('');$('activate').hidden=false;}catch(e){error(e);}}
 $('language').onchange=()=>{lang=$('language').value;translate();};
 $('activate').onsubmit=async event=>{event.preventDefault();if($('password').value!==$('confirm').value){status(t.mismatch,true);return;}if(!$('activate').reportValidity())return;$('submit').disabled=true;status(t.busy);try{await api('accept',{password:$('password').value,terms_version:termsVersion,consent:$('consent').checked});$('password').value=$('confirm').value='';sessionStorage.removeItem('lignoai-invitation');token='';$('activate').hidden=true;$('done').hidden=false;status('');$('ready').tabIndex=-1;$('ready').focus();}catch(e){error(e);}finally{$('submit').disabled=false;}};
 $('renew').onclick=async()=>{$('renew').disabled=true;try{await api('renew');status(t.sent);$('renew').hidden=true;sessionStorage.removeItem('lignoai-invitation');token='';}catch(e){error(e);}finally{$('renew').disabled=false;}};
 window.addEventListener('hashchange',()=>{if(new URLSearchParams(location.hash.slice(1)).has('token'))location.reload();});
 translate();if(/^[a-f0-9]{64}$/.test(token))inspect();else status(t.invalid_invitation,true);
})();
