const {chromium}=require('C:/Users/sebas/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{
 const root=path.resolve(__dirname,'..'),out=path.join(root,'tmp/invitation-qa');fs.mkdirSync(out,{recursive:true});
 const page=await browser.newPage({viewport:{width:1100,height:1000}}),errors=[],calls=[];let mode='valid';page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const inv={id:'test-id',first_name:'Alex',last_name:'Beispiel',email:'alex@example.test',organization:'Beispielbüro',license_months:null,max_devices:1,lang:'de'};
 await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.pathname.endsWith('/partner-invitations')){const b=route.request().postDataJSON();calls.push(b.action);if(b.action==='inspect')return route.fulfill({status:mode==='expired'?410:200,json:mode==='expired'?{error:'expired'}:{invitation:inv,terms_version:'2026-09-24'}});if(b.action==='accept'){assert.equal(b.consent,true);assert.equal(b.terms_version,'2026-09-24');return route.fulfill({json:{accepted:true,email:inv.email}});}if(b.action==='renew')return route.fulfill({json:{sent:true}});if(b.action==='prepare')assert.equal(b.license_months,null);return route.fulfill({json:{invitations:b.action==='list'?[]:[inv]}});}
 if(u.pathname.endsWith('/license-admin'))return route.fulfill({json:{accounts:[]}});
 if(u.hostname==='cdn.jsdelivr.net')return route.fulfill({contentType:'application/javascript',body:`window.supabase={createClient:()=>({auth:{onAuthStateChange:fn=>queueMicrotask(()=>fn('INITIAL_SESSION',{access_token:'fixture',user:{email:'admin@example.test'}})),signOut:()=>{}}})};`});
 const f=path.join(root,decodeURIComponent(u.pathname));if(!f.startsWith(root+path.sep)||!fs.existsSync(f))return route.fulfill({status:404,body:''});if(u.pathname==='/admin.html')return route.fulfill({contentType:'text/html',body:fs.readFileSync(f,'utf8').replace(/integrity="[^"]*"/g,'')});return route.fulfill({path:f});});
 const url='https://lignoai.ch/einladung.html#token='+'a'.repeat(64);
 await page.goto(url);await page.locator('#activate').waitFor({state:'visible'});assert.equal(new URL(page.url()).hash,'');assert.deepEqual(calls,['inspect']);assert.equal(await page.locator('#email').innerText(),inv.email);assert.match(await page.locator('#licence').innerText(),/Widerruf/);
 await page.screenshot({path:path.join(out,'01-activate.png')});
 for(const lang of ['fr','it','en','de']){await page.selectOption('#language',lang);assert.equal(await page.locator('html').getAttribute('lang'),lang);assert.ok((await page.locator('#submit').innerText()).length>5);}
 await page.fill('#password','Example-Test2026!');await page.fill('#confirm','Other-Test2026!');await page.check('#consent');await page.click('#submit');assert.match(await page.locator('#status').innerText(),/stimmen nicht/);assert.equal(calls.filter(x=>x==='accept').length,0);
 await page.fill('#confirm','Example-Test2026!');await page.click('#submit');await page.locator('#done').waitFor({state:'visible'});assert.equal(await page.locator('#password').inputValue(),'');assert.equal(await page.evaluate(()=>sessionStorage.getItem('lignoai-invitation')),null);await page.screenshot({path:path.join(out,'02-ready.png')});
 mode='expired';await page.goto(url);await page.locator('#renew').waitFor({state:'visible'});assert.equal(await page.locator('#activate').isVisible(),false);await page.click('#renew');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('neueste'));assert.equal(calls.filter(x=>x==='renew').length,1);
 mode='valid';await page.setViewportSize({width:390,height:844});await page.goto(url);await page.locator('#activate').waitFor({state:'visible'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,'03-mobile.png')});
 await page.setViewportSize({width:1200,height:1000});await page.goto('https://lignoai.ch/admin.html');await page.locator('#adminView').waitFor({state:'visible'});await page.locator('#partnerInvites summary').click();await page.fill('#inviteFirst','Alex');await page.fill('#inviteLast','Beispiel');await page.fill('#inviteEmail','alex@example.test');await page.fill('#inviteOrg','Beispielbüro');await page.selectOption('#inviteMonths','');await page.getByRole('button',{name:'Einladung vorbereiten',exact:true}).click();await page.locator('#inviteList .invite-row').waitFor({state:'visible'});assert.equal(calls.filter(x=>x==='send').length,0);await page.screenshot({path:path.join(out,'04-admin.png')});await page.getByRole('button',{name:'Einladung senden',exact:true}).click();assert.equal(calls.filter(x=>x==='send').length,1);
 assert.deepEqual(errors,[]);console.log('PASS invitation browser: preview does not consume, identity, four languages, password repeat, explicit acceptance, clean success/download, expired renewal, mobile and admin prepare/send separation.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
